# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4faca823bdad890ddd34868931c917ebaf9dcd87157f355495b9235fbf8fc3d76642dbcec846ab198074e86da4673f9aeea5d13e7aa9e14709e90ba963a9814

test:
  secret_key_base: 5437636222ecd2987be9091e67270ebdd42071579a89726fdec17510948c147076f97fab1770687840500aabd43bc279c76f7b1c2da74e3946c3346452b42ff3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
